//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public car()
        {
            this.contract = new HashSet<contract>();
        }
    
        public int id { get; set; }
        public int car_type_id { get; set; }
        public Nullable<int> state { get; set; }
        public string name { get; set; }
        public string registration_number { get; set; }
        public Nullable<int> mileage { get; set; }
        public Nullable<bool> aircon { get; set; }
        public Nullable<bool> navigation { get; set; }
        public Nullable<bool> transmission_type { get; set; }
        public Nullable<int> power { get; set; }
        public string picture_link { get; set; }
        public string parking_pos { get; set; }
    
        public virtual ICollection<contract> contract { get; set; }
        public virtual car_type car_type { get; set; }
    }
}
