//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public car()
        {
            this.contract = new HashSet<contract>();
        }
    
        public int id { get; set; }
        public int car_type_id { get; set; }
        public int user_id { get; set; }
        public string registration_number { get; set; }
        public string name { get; set; }
        public int state { get; set; }
        public int mileage { get; set; }
        public string picture_link { get; set; }
        public string position { get; set; }
        public int power { get; set; }
        public bool aircon { get; set; }
        public bool navigation_system { get; set; }
        public int transmission { get; set; }
    
        public virtual car_type car_type { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<contract> contract { get; set; }
    }
}
