//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_type
    {
        public car_type()
        {
            this.car = new HashSet<car>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public Nullable<int> @class { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> seat_size { get; set; }
    
        public virtual ICollection<car> car { get; set; }
    }
}
