//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_type
    {
        public car_type()
        {
            this.car = new HashSet<car>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public int size { get; set; }
        public int @class { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<car> car { get; set; }
    }
}
