//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarSharingEntities : DbContext
    {
        public CarSharingEntities()
            : base("name=CarSharingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<car_type> car_type { get; set; }
        public virtual DbSet<contract> contract { get; set; }
        public virtual DbSet<user_account> user { get; set; }
        public virtual DbSet<user_address> user_address { get; set; }
    }
}
