//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int car_id { get; set; }
        public System.DateTime pick_up_date { get; set; }
        public System.DateTime return_date { get; set; }
        public string start_location { get; set; }
        public string end_location { get; set; }
        public Nullable<int> distance { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual car car { get; set; }
        public virtual user_account user { get; set; }
    }
}
