//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.car = new HashSet<car>();
            this.contract = new HashSet<contract>();
            this.user_address = new HashSet<user_address>();
        }
    
        public int id { get; set; }
        public string login_name { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string name { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string identity_number { get; set; }
        public string email { get; set; }
        public int access_state { get; set; }
    
        public virtual ICollection<car> car { get; set; }
        public virtual ICollection<contract> contract { get; set; }
        public virtual ICollection<user_address> user_address { get; set; }
    }
}
