//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user_account
    {
        public user_account()
        {
            this.contract = new HashSet<contract>();
            this.user_address = new HashSet<user_address>();
        }
    
        public int id { get; set; }
        [Required]
        public string login_name { get; set; }
        [Required]
        public string firstname { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public System.DateTime date_of_birth { get; set; }
        public Nullable<System.Guid> identity_number { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        public string password { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string email { get; set; }
        public Nullable<int> access_state { get; set; }
        public Nullable<System.DateTime> timelimit { get; set; }
        public Nullable<System.DateTime> remove_date { get; set; }
    
        public virtual ICollection<contract> contract { get; set; }
        public virtual ICollection<user_address> user_address { get; set; }
    }
}
